W7D5/practice-for-ch-rails-goal-app-refactor-main/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:index, :show, :new, :create]
  resources :goals do
    resources :cheers, only: [:create]
  end
  resources :cheers, only: [:index]
  resources :user_comments, only: [:create]
  resources :goal_comments, only: [:create]
end

W7D5/practice-for-ch-rails-goal-app-refactor-main/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  cheer_count     :integer          not null
#
class User < ApplicationRecord
  validates :session_token, presence: true
  validates :username, uniqueness: true, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :password_digest, presence: { message: 'Password can\'t be blank.' }
  validates :cheer_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  
  attr_reader :password

  before_validation :ensure_session_token, :ensure_cheer_count

  has_many :goals, 
    foreign_key: :author_id,
    dependent: :destroy,
    inverse_of: :author

  has_many :comments,
    foreign_key: :recipient_id,
    class_name: :UserComment,
    dependent: :destroy,
    inverse_of: :recipient

  has_many :authored_comments, 
    foreign_key: :author_id,
    class_name: :UserComment,
    dependent: :destroy,
    inverse_of: :author

  has_many :cheers_given,
    class_name: :Cheer,
    foreign_key: :giver_id,
    dependent: :destroy,
    inverse_of: :giver

  has_many :cheers_received,
    through: :goals,
    source: :cheers

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    # `user&.is_password?(password)` is syntactic sugar for
    # `user && user.is_password?(password)`
    user&.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = generate_unique_session_token
    self.save!
    self.session_token
  end

  def is_password?(maybe_password)
    BCrypt::Password.new(self.password_digest).is_password?(maybe_password)
  end

  def password=(new_pw)
    @password = new_pw
    self.password_digest = BCrypt::Password.create(new_pw)
  end

  def decrement_cheer_count!
    self.cheer_count -= 1
    self.save!
  end

  private

  def generate_unique_session_token
    # `SecureRandom::urlsafe_base64` does not guarantee uniqueness. Wrapping
    # this call in a loop ensures that no other user has the generated token.
    loop do
      session_token = SecureRandom::urlsafe_base64(16)
      return session_token unless User.exists?(session_token: session_token)
    end
  end

  def ensure_session_token
    self.session_token ||= generate_unique_session_token
  end

  def ensure_cheer_count
    self.cheer_count ||= Cheer::CHEER_LIMIT
  end
end

W7D5/practice-for-ch-rails-goal-app-refactor-main/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_current_user!, only: %i[new create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

W7D5/practice-for-ch-rails-goal-app-refactor-main/app/views/users/index.html.erb
<h2>Users</h2>

<% @users.each do |user| %>
  <a href="<%= user_url(user) %>"><%= user.username %></a>
<% end %>

W7D5/practice-for-ch-rails-goal-app-refactor-main/app/views/users/new.html.erb
<h2>Sign Up!</h2>

<%= render "shared/user_form", user: @user, type: :newuser %>

W7D5/practice-for-ch-rails-goal-app-refactor-main/app/views/users/show.html.erb
<div class="profile">
  <h2><%= @user.username.capitalize %>'s Profile</h2>

  <div class="profile-section">
    <% @user.comments.each do |comment| %>
      <p><%= comment.body %></p>
    <% end %>

    <%= render "shared/comments_form", receiver_id: @user.id, comment_type: "User" %>
  </div>

  <div class="profile-section">
    <h3><%= @user.username.capitalize %>'s Goals:</h3>

    <% if @user == current_user %>
      <a href="<%= new_goal_url %>">New Goal</a>
      <a href="<%= cheers_url %>">My Cheers!</a>
    <% end %>

    <ul>
      <% @user.goals.each do |goal| %>
        <% if (current_user && current_user.id == @user.id) || !(goal.private) %>
          <%= render "shared/show_goal_basics", goal: goal %>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

<div class="all-users">
  <a href="<%= users_url %>">All Users</a>
</div>